# data:
body_model_dir: ../body_models/smpl_skeleton.npz
input_n: 10  # number of model's input frames

# gen_model:
n_stgcnn_layers: 9  # number of stgcnn layers
n_ccnn_layers: 2  # number of layers for the Coordinate-Channel Convolution
ccnn_kernel_size: [1, 1]  # kernel for the C-CNN layers
tcnn_kernel_size: [3, 3]  # kernel for the Time-Extrapolator CNN layers
n_tcnn_layers: 4  # number of layers for the Time-Extrapolator Convolution
tcnn_dropout: 0.0  # tcnn dropout
embedding_dim: 40  # dimensions for the coordinates of the embedding
input_dim: 3  # dimensions of the input coordinates
st_gcnn_dropout: 0.1  # st-gcnn dropout
ccnn_dropout: 0.0  # ccnn dropout

# attention:
n_head: 6
transformer_decoder_n_layers: 3

# simple_rnn:
input_dropout_rate: 0.1
input_hidden_size: 256
cell_size: 1024
output_hidden_size: 960  # 64 for with SPL, 960 for without

# disc_model:
disc_model: motion_disc
disc_gamma: 0.1
disc_milestones: [15, 25, 35, 40]
disc_clip_grad: 5.0

# run:
gen_optimizer: adam
disc_optimizer: adam
gen_scheduler: multi_step_lr
disc_scheduler: multi_step_lr
seed: 42
n_epochs: 100  # number of epochs to train
num_workers: 5  # 0 means use the same thread for preparing data
gen_weight_decay: 0.00001
disc_lr: 0.01
disc_weight_decay: 0.00001
gen_disc_loss_weight: 0.01
start_training_discriminator_epoch: 0
start_feeding_discriminator_loss_epoch: 0
use_scheduler: True  # use MultiStepLR scheduler
log_dir: ../logs/
print_train_loss_every_iter: 1000
